CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name_first VARCHAR(100) NOT NULL,
  name_last VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,  
  country VARCHAR(2),
  age INT,
  bio TEXT,
  picture BLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);