CREATE TABLE IF NOT EXISTS group_relations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  group_id INT NOT NULL,
  follower BINARY NOT NULL,
  member BINARY NOT NULL,
  organizer BINARY NOT NULL,
  member_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);