CREATE TABLE IF NOT EXISTS group_relations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  group_id INT NOT NULL,
  follower BINARY NOT NULL DEFAULT 0,
  member BINARY NOT NULL DEFAULT 0,
  organizer BINARY NOT NULL DEFAULT 0,
  member_at DATETIME DEFAULT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  FOREIGN KEY (group_id) REFERENCES `groups`(id) ON DELETE CASCADE
);